### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by MartinThoma** [MartinThoma/hwrt#17]
Check if `hwrt` works on Windows machines. What are the exact error messages?

**Comment by thesunlover** [comment]
Hello, Martin
I just met your hwrtool
I work on my notebook
I have 8GB RAM.
I started getting some errors.
I wish to work on the project with you as much as I am able.
During download.py execution I got MemoryError when calling is_file_consistent()
The file would need to be read in chunks in my opinion.

**Comment by MartinThoma** [comment]
Hello Iskren,

Thanks for your feedback!

Could you please paste the error message? I don't use Windows, so testing is a bit difficult for me.

**Comment by thesunlover** [comment]
Of course, sure.

Traceback (most recent call last):
  File "hwrt\download.py", line 58, in <module>
    main()
  File "hwrt\download.py", line 43, in main
    while not is_file_consistent(local_path_file, dataset['md5']) and i < 3:
  File "hwrt\download.py", line 21, in is_file_consistent
    hashlib.md5(open(local_path_file, 'rb').read()).hexdigest() == md5_hash
MemoryError

**Comment by MartinThoma** [comment]
Thank you :-)

I guess the solution is http://stackoverflow.com/a/1131238/562769
I'll try that tomorrow (I can get access to windows computers at university).

**Comment by thesunlover** [comment]
:) YES

just a note:
http://stackoverflow.com/a/1131255/3345926
this one is better
i can apply it and make a pull request (PR) for you, if you dont mind, because I saw this is your Phd project

**Comment by MartinThoma** [comment]
Oh, no, this is not my PhD project. It was a project for my bachelors
thesis and I will continue working on it in my masters thesis.

Feel free to add the pull request.

**Comment by thesunlover** [comment]
can we add somewhere in the documentation that there are already some precompiled libs here:
http://www.lfd.uci.edu/~gohlke/pythonlibs/#h5py

I also noticed that when I downloaded the big data file via Google Chrome browser it took 5-10 times less than compared to download.py process ()

**Comment by thesunlover** [comment]
clarification on previous message
http://www.lfd.uci.edu/~gohlke/pythonlibs/6icuform/h5py-2.4.0-cp27-none-win32.whl
h5py  Cythoning has some problems

**Comment by thesunlover** [comment]
Traceback (most recent call last):
  File "hwrt\serve.py", line 295, in <module>
    main(args.port)
  File "hwrt\serve.py", line 281, in main
    output_semantics) = utils.load_model(model_file)
  File "C:\Python27\lib\site-packages\hwrt\utils.py", line 492, in load_model
    model = nntoolkit.utils.get_model(model_file)
  File "C:\Python27\lib\site-packages\nntoolkit\utils.py", line 132, in get_model
    shutil.rmtree(tarfolder)
  File "C:\Python27\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Python27\lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 32] The process cannot access the file because it is being
used by another process: 'c:\\users\\ceco\\appdata\\local\\temp\\tmpsmcbqr\\W2.hdf5'

**Comment by retsyo** [comment]
yes, I met the problem stated by thesunlover

**Comment by retsyo** [comment]
yes, I met the problem stated by thesunlover

**Comment by retsyo** [comment]
yes, I met the problem stated by thesunlover

**Comment by MartinThoma** [comment]
I can confirm, but sadly don't have the time to fix this. This is the reason why I put it on [INACTIVE](https://github.com/MartinThoma/hwrt/blob/master/setup.cfg#L26) (to be honest, I also forgot this PR)
