### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'

### ISSUE THREAD

**Issue by MartinThoma** [MartinThoma/hwrt#20]
When running the worker, the following bug occurs for some recordings:

```bash
    TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
    2015-03-28 13:06:42,740 INFO 127.0.0.1 - - [28/Mar/2015 13:06:42] "GET /work?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
    2015-03-28 13:06:42,741 INFO 127.0.0.1 - - [28/Mar/2015 13:06:42] "GET /work?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
    2015-03-28 13:06:42,742 INFO 127.0.0.1 - - [28/Mar/2015 13:06:42] "GET /work?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
    2015-03-28 13:06:42,893 INFO 127.0.0.1 - - [28/Mar/2015 13:06:42] "GET /work?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
    2015-03-28 13:06:42,904 INFO 127.0.0.1 - - [28/Mar/2015 13:06:42] "GET /work?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 -
    2015-03-28 13:06:42,961 INFO 127.0.0.1 - - [28/Mar/2015 13:06:42] "GET /work?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
    2015-03-28 13:31:15,581 INFO Start working!
    http://www.martin-thoma.de/write-math/view/?raw_data_id=295246
    2015-03-28 13:31:17,264 INFO 127.0.0.1 - - [28/Mar/2015 13:31:17] "GET /work HTTP/1.1" 500 -
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
        return self.wsgi_app(environ, start_response)
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
        response = self.make_response(self.handle_exception(e))
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
        response = self.full_dispatch_request()
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
        rv = self.dispatch_request()
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/usr/local/lib/python2.7/dist-packages/hwrt-0.1.211-py2.7.egg/hwrt/serve.py", line 238, in work
        raw_data_json)
      File "/usr/local/lib/python2.7/dist-packages/hwrt-0.1.211-py2.7.egg/hwrt/utils.py", line 518, in evaluate_model_single_recording_preloaded
        handwriting.preprocessing(preprocessing_queue)
      File "/usr/local/lib/python2.7/dist-packages/hwrt-0.1.211-py2.7.egg/hwrt/HandwrittenData.py", line 126, in preprocessing
        algorithm(self)
      File "/usr/local/lib/python2.7/dist-packages/hwrt-0.1.211-py2.7.egg/hwrt/preprocessing.py", line 224, in __call__
        "time": p["time"] - mint}
    TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
    2015-03-28 13:31:17,518 INFO 127.0.0.1 - - [28/Mar/2015 13:31:17] "GET /work?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
    2015-03-28 13:31:17,523 INFO 127.0.0.1 - - [28/Mar/2015 13:31:17] "GET /work?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
    2015-03-28 13:31:17,528 INFO 127.0.0.1 - - [28/Mar/2015 13:31:17] "GET /work?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
    2015-03-28 13:31:17,664 INFO 127.0.0.1 - - [28/Mar/2015 13:31:17] "GET /work?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
    2015-03-28 13:31:17,669 INFO 127.0.0.1 - - [28/Mar/2015 13:31:17] "GET /work?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 -
    2015-03-28 13:31:17,709 INFO 127.0.0.1 - - [28/Mar/2015 13:31:17] "GET /work?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
```

**Comment by MartinThoma** [comment]
The problem was that some JSON recordings have `time: null`.
